<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Exercices Formulaires</title>
        <link rel="stylesheet" href="assets/styles/style.css">
    </head>
    <body>
        <?php require "templates/partials/_header.phtml" ?>
        <?php if($template === "homepage") {
                require "templates/partials/_homepage.phtml";}
            else if($template === "about") {
                require "templates/partials/_about.phtml";}
            else if($template ==="contact") {
                require "templates/partials/_contact.phtml";}?>
        <?php require "templates/partials/_footer.phtml" ?>
    </body>
</html>