<main>
    <h2>
        <?= $pageTitle; ?>
    </h2>
    <!-- Votre formulaire ici -->
        <form method="post" action="controllers/user-form.php">
            <label for="email">Votre mail : </label>
            <input type="email" name="email">
            <br>
            <label for="password">Votre mot de passe : </label>
            <input type="password" name="password">
            <br>
            <label for="password-confirm">Votre mot de passe : </label>
            <input type="password" name="password-confirm">
            <br>
            <input type="checkbox" name="newsletter">
            <label for="newsletter">S'inscrire à la newsletter</label>
            <br>
            <button type="submit">Connexion</button>
        </form>
</main>